# Generated by Django 5.1.4 on 2025-01-03 08:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Fuel_Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("P", "Petrol"),
                            ("D", "Diesel"),
                            ("E", "Electric"),
                            ("H", "Hydrogen"),
                            ("C", "Compressed Natural Gas"),
                            ("X", "Hybrid"),
                        ],
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Performance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("top_speed", models.IntegerField(help_text="Top speed in km/h")),
                (
                    "acceleration_min",
                    models.FloatField(
                        help_text="Minimal acceleration time from 0 to 100 km/h in seconds",
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                (
                    "acceleration_max",
                    models.FloatField(
                        help_text="Maximal acceleration time from 0 to 100 km/h in seconds",
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TagCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("brand", "Brand"),
                            ("fuel_type", "Fuel Type"),
                            ("engine", "Engine"),
                            ("seats", "Seats"),
                            ("price_range", "Price Range"),
                            ("displacement", "Displacement"),
                            ("performance_metrics", "Performance Metrics"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField()),
                ("seats", models.CharField(max_length=10)),
                ("year", models.IntegerField(default=2024)),
                ("price_min", models.IntegerField()),
                ("price_max", models.IntegerField()),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cars.brand"
                    ),
                ),
                ("fuel_type", models.ManyToManyField(to="cars.fuel_type")),
                (
                    "performance",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cars.performance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Engine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cylinder_layout",
                    models.CharField(
                        choices=[
                            ("I", "Inline/Straight"),
                            ("V", "V"),
                            ("F", "Flat/Boxer"),
                            ("W", "W"),
                            ("R", "Rotary/Wankel"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "cylinder_count",
                    models.PositiveSmallIntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(32),
                        ],
                    ),
                ),
                (
                    "aspiration",
                    models.CharField(
                        choices=[
                            ("T", "Turbocharged"),
                            ("S", "Supercharged"),
                            ("W", "Twin Turbo"),
                            ("Q", "Quad Turbo"),
                            ("N", "Naturally Aspirated"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "engine_capacity",
                    models.PositiveIntegerField(
                        help_text="Engine capacity in cc", null=True
                    ),
                ),
                (
                    "battery_capacity",
                    models.FloatField(help_text="Battery capacity in kWh", null=True),
                ),
                (
                    "horsepower",
                    models.PositiveIntegerField(help_text="Horsepower in hp"),
                ),
                ("torque", models.PositiveIntegerField(help_text="Torque in Nm")),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cars.car"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=50)),
                ("cars", models.ManyToManyField(to="cars.car")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cars.tagcategory",
                    ),
                ),
            ],
            options={
                "unique_together": {("value", "category")},
            },
        ),
    ]
