# Generated by Django 5.1.4 on 2025-01-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Fuel_Type",
            new_name="FuelType",
        ),
    ]
