# Generated by Django 5.1.4 on 2025-01-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="price_max",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="price_min",
            field=models.IntegerField(null=True),
        ),
    ]
