# Generated by Django 5.1.4 on 2025-01-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_alter_brand_options_alter_car_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True),
        ),
    ]
