# Generated by Django 5.1.4 on 2025-01-05 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_alter_car_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="performance",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cars.performance",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="price_max",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="price_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="engine",
            name="aspiration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("T", "Turbocharged"),
                    ("S", "Supercharged"),
                    ("W", "Twin Turbo"),
                    ("Q", "Quad Turbo"),
                    ("N", "Naturally Aspirated"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="engine",
            name="battery_capacity",
            field=models.FloatField(blank=True, help_text="Unit: kWh", null=True),
        ),
        migrations.AlterField(
            model_name="engine",
            name="cylinder_count",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="engine",
            name="cylinder_layout",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I", "Inline/Straight"),
                    ("V", "V"),
                    ("F", "Flat/Boxer"),
                    ("W", "W"),
                    ("R", "Rotary/Wankel"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="engine",
            name="engine_capacity",
            field=models.PositiveIntegerField(
                blank=True, help_text="Unit: cc", null=True
            ),
        ),
        migrations.AlterField(
            model_name="engine",
            name="horsepower",
            field=models.PositiveIntegerField(
                blank=True, help_text="Unit: hp", null=True
            ),
        ),
        migrations.AlterField(
            model_name="engine",
            name="torque",
            field=models.PositiveIntegerField(
                blank=True, help_text="Unit: Nm", null=True
            ),
        ),
        migrations.AlterField(
            model_name="performance",
            name="acceleration_max",
            field=models.FloatField(blank=True, help_text="Unit: seconds", null=True),
        ),
        migrations.AlterField(
            model_name="performance",
            name="acceleration_min",
            field=models.FloatField(blank=True, help_text="Unit: seconds", null=True),
        ),
        migrations.AlterField(
            model_name="performance",
            name="top_speed",
            field=models.IntegerField(blank=True, help_text="Unit: km/h", null=True),
        ),
    ]
